import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from '@/context/AuthContext';
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";


const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Eventura",
  description: "Generated by Backspace",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={poppins.className}
      >
        <AuthContextProvider>
          <Navbar/>
          <main className="bg-[#111827] min-h-screen">
          {children}
          </main>
          <Footer/>
          </AuthContextProvider>
      </body>
    </html>
  );
}
