import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/AuthContext";
import { TelegramAuthContextProvider } from "@/context/TelegramAuthContext";
import { EventContextProvider } from "@/context/EventContext";
import { ContractContextProvider } from "@/context/ContractContext";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Eventura",
  description: "Generated by Backspace",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className} suppressHydrationWarning={true}>
        <AuthContextProvider>
          <ContractContextProvider>
            <TelegramAuthContextProvider>
              <EventContextProvider>
                <Navbar />
                <main
                  className="bg-[#1118272a] min-h-screen py-16"
                  style={{
                    backgroundImage: `linear-gradient(rgba(0, 0, 0, 0.6), rgba(0, 0, 0, 0.7)), url('/bg.jpg')`,
                    backgroundRepeat: 'no-repeat',
                    backgroundSize: 'cover',
                    backgroundPosition: 'center',
                    minHeight: '100vh',
                  }}
                >
                  {children}
                </main>
                <Footer />
              </EventContextProvider>
            </TelegramAuthContextProvider>
          </ContractContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
