import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "../../flow-config";
import { AuthContextProvider } from "@/context/AuthContext";
import { TelegramAuthContextProvider } from "@/context/TelegramAuthContext";
import { EventContextProvider } from "@/context/EventContext";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Eventura",
  description: "Generated by Backspace",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className} suppressHydrationWarning={true}>
        <AuthContextProvider>
          <TelegramAuthContextProvider>
            <EventContextProvider>
              <Navbar />
              <main className="bg-[#111827] min-h-screen py-16">
                {children}
              </main>
              <Footer />
            </EventContextProvider>
          </TelegramAuthContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
